name: cd-cd pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          registry-url: https://npm.pkg.github.com/
      # - name: build
      #   run: npm run build:all
      # - name: test
      #   run: npm run test:all
      - run: npm ci
      - name: publish
        run: npm run publish:all
