name: cd-cd pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm i
      - name: build
        run: npm run build:all
      - name: test
        run: npm run test:all
      - run: npm ci
      - name: publish
        run: npm run publish:all
        env:
          GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}
