name: cd-cd pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

permissions:
  contents: read
  deployments: write
  id-token: write
  packages: write
  pages: write

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    container:
      image: node:20.9.0-slim
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm i
      - name: build
        run: npm run build:all
      - name: test
        run: npm run test:all
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      # - name: publish
      #   run: npm run publish:all
